import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#fff1df',
        'surface-bright': '#f8f7f0',
        'tertiary-fixed': '#c1fd7c',
        'inverse-primary': '#feb300',
        'primary-container': '#feb300',
        'error-dim': '#b92902',
        'on-error-container': '#520c00',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#feb300',
        'on-primary-fixed-variant': '#5e4000',
        'primary-fixed-dim': '#eda600',
        'on-tertiary-container': '#396100',
        'surface-variant': '#ddddd5',
        tertiary: '#3c6600',
        'on-secondary': '#eaf4ff',
        'on-secondary-fixed': '#003854',
        'on-background': '#2e2f2b',
        'surface-container-high': '#e3e3db',
        'surface-tint': '#7b5400',
        error: '#b02500',
        'surface-container-highest': '#ddddd5',
        background: '#f8f7f0',
        'surface-dim': '#d4d5cc',
        'secondary-container': '#a6d7ff',
        'outline-variant': '#adada7',
        'error-container': '#f95630',
        'tertiary-dim': '#345900',
        surface: '#f8f7f0',
        outline: '#777772',
        'on-surface': '#2e2f2b',
        'secondary-dim': '#00557d',
        'on-tertiary-fixed-variant': '#406c00',
        'inverse-surface': '#0d0f0b',
        'on-tertiary-fixed': '#2c4d00',
        'on-error': '#ffefec',
        secondary: '#00618f',
        primary: '#7b5400',
        'secondary-fixed': '#a6d7ff',
        'primary-dim': '#6b4900',
        'secondary-fixed-dim': '#86cbff',
        'on-primary-fixed': '#382400',
        'inverse-on-surface': '#9d9d97',
        'tertiary-container': '#c1fd7c',
        'on-primary-container': '#523700',
        'tertiary-fixed-dim': '#b3ee6f',
        'on-secondary-fixed-variant': '#00567e',
        'surface-container-low': '#f2f1ea',
        'surface-container': '#e9e9e1',
        'on-secondary-container': '#004c71',
        'on-surface-variant': '#5b5c57',
        'on-tertiary': '#d9ffab',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
